apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: webapp
    meta.helm.sh/release-namespace: webapp
  creationTimestamp: "2023-12-03T20:43:38Z"
  generation: 1
  labels:
    app: webapp-webapp
    app.kubernetes.io/managed-by: Helm
  name: webapp-csye7125
  namespace: webapp
  resourceVersion: "6068252"
  uid: d69ab658-14c9-46e4-b510-489ad677b702
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 120
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: webapp-webapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp-webapp
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - webapp-webapp
            topologyKey: topology.kubernetes.io/zone
      containers:
      - env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: webapp-secrets
        - name: DB_USERNAME
          value: postgres
        - name: DB_HOST
          value: webapp-postgresql-0.webapp-postgresql-hl.webapp.svc.cluster.local
        - name: DB_NAME
          value: app
        - name: DB_PORT
          value: "5432"
        - name: APP_PORT
          value: "4000"
        image: sumanthksai/webapp:1.10.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: csye7125-webapp
        ports:
        - containerPort: 4000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 4000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /flyway/conf
          name: flyway-config-volume
        - mountPath: /flyway/db_password.txt
          name: secret-volume
          subPath: db_password.txt
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: webapp-docker-regcred
      initContainers:
      - command:
        - flyway
        - migrate
        - -configFiles=/flyway/conf/flyway.conf
        - -locations=filesystem:/flyway/sql
        - -connectRetries=60
        image: sumanthksai/csye7125-flyway:latest
        imagePullPolicy: Always
        name: flyway-migrate
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /flyway/conf
          name: flyway-config-volume
        - mountPath: /flyway/db_password.txt
          name: secret-volume
          subPath: db_password.txt
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: webapp-service-account
      serviceAccountName: webapp-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: webapp-configs
        name: flyway-config-volume
      - name: secret-volume
        secret:
          defaultMode: 420
          secretName: webapp-secrets
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2023-12-03T20:45:19Z"
    lastUpdateTime: "2023-12-03T20:45:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-12-03T20:43:38Z"
    lastUpdateTime: "2023-12-03T20:45:19Z"
    message: ReplicaSet "webapp-csye7125-5b4b78788b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
