apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-config
data:
  flyway.conf: |
    flyway.url=jdbc:postgresql://host.docker.internal:5432/postgres
    flyway.user=postgres
    flyway.password=password
    flyway.locations=filesystem:/flyway/sql
