apiVersion: apps/v1
kind: StatefulSet
metadata:
   name: csye7125-db
   labels:
     "app" : "postgres"
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: "postgres"
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash","-c","sleep 20 && PGPASSWORD=password psql -a -f /scripts/init-db.sql -U postgres"]
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: DB_USERNAME
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: DB_NAME
            - name: HOST_DIRECTORY
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: HOST_DIRECTORY
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: scripts
          configMap:
            name: configs

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432  
      targetPort: 5432
  externalTrafficPolicy: Cluster


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/${HOST_DIRECTORY} 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
