apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-config
data:
  flyway.conf: |
    flyway.url=jdbc:mysql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)
    flyway.user=$(DB_USERNAME)
    flyway.password=$(DB_PASSWORD)
