apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-config
data:
  flyway.conf: |
    flyway.url=jdbc:postgresql://host.docker.internal:5432/app
    flyway.user=postgres
    flyway.password=Asdfghjklz@2
    flyway.baselineOnMigrate=false
