apiVersion: apps/v1
kind: Deployment
metadata:
   name: csye7125
   labels:
     "app" : "webapp"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "webapp"
  template:
      metadata:
       labels:
        app: webapp
      spec:
        containers:
        - name: csye7125-webapp
          image: sumanthksai/group-csye7125:latest
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: DB_PORT
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: APP_PORT
          ports:
          - containerPort: 4000
          readinessProbe:
            httpGet:
              path: /healthz  
              port: 4000      
            initialDelaySeconds: 5  
            periodSeconds: 10       
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 10

        initContainers:
        - name: flyway-migrate
          image: sumanthksai/flyway:latest
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: DB_PORT
          volumeMounts:
            - name: flyway-config-volume
              mountPath: /flyway/conf
          command: ["flyway","migrate", "-configFiles=/flyway/conf/flyway.conf" ,"-locations=filesystem:/flyway/sql" , "-connectRetries=60"] 
        volumes:
        - name: flyway-config-volume
          configMap:
            name: flyway-config

    

    
  