apiVersion: apps/v1
kind: Deployment
metadata:
   name: csye7125-webapp
   labels:
     "app" : "webapp"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "webapp"
  template:
      metadata:
       labels:
        app: webapp
      spec:
        containers:
        - name: csye7125-webapp
          image: sumanthksai/webapp:latest
          ports:
          - containerPort: 4000
        initContainers:
        - name: flyway-migrate
          image: sumanthksai/flyway:1.2
          command: ["flyway","migrate", "-configFiles=/flyway/conf/flyway.config" ,"-locations=filesystem:/flyway/sql" , "-connectRetries=60"] 

    

    
  