apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
data:
{{- if .Values.configMap.enabled }}
  flyway.conf: |
    flyway.url=jdbc:postgresql://{{ .Release.Name }}-postgresql-0.{{ .Release.Name }}-postgresql-hl.{{ .Release.Namespace }}.svc.cluster.local/app
{{ .Values.configMap.data.flyway | nindent 4 }}
{{- end }}
