apiVersion: apps/v1
kind: Deployment
metadata:
   name: csye7125
   labels:
     "app" : "webapp"
spec:
  replicas: {{ .Values.deployment.replicas }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  progressDeadlineSeconds: {{ .Values.deployment.progressDeadlineSeconds }}
  selector:
    matchLabels:
      app: "webapp"
  template:
      metadata:
       labels:
        app: webapp
      spec:
        containers:
        - name: {{ .Values.primaryContainer.name }}
          image: {{ .Values.primaryContainer.repository }}:{{ .Values.primaryContainer.tag }}
          imagePullPolicy: {{ .Values.primaryContainer.pullPolicy }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: DB_PASSWORD
            - name: DB_USERNAME
              value: {{.Values.postgresql.auth.username}}
            - name: DB_HOST
              value: {{ .Release.Name }}-postgresql-0.{{ .Release.Name }}-postgresql-hl.{{ .Release.Namespace }}.svc.cluster.local
            {{- range .Values.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote  }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.primaryContainer.ports.containerPort }}
          volumeMounts:
          {{- range .Values.initContainer.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.primaryContainer.readinessProbe.httpGet.path }}
              port: {{ .Values.primaryContainer.ports.containerPort }}
            initialDelaySeconds: {{ .Values.primaryContainer.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.primaryContainer.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.primaryContainer.livenessProbe.httpGet.path }}
              port: {{ .Values.primaryContainer.ports.containerPort }}
            initialDelaySeconds: {{ .Values.primaryContainer.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.primaryContainer.livenessProbe.periodSeconds }}
        initContainers:
        {{- if .Values.initContainer.enabled }}
          - name: {{ .Values.initContainer.name }}
            image: {{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}
            volumeMounts:
            {{- range .Values.initContainer.volumeMounts }}
              - name: {{ .name }}
                mountPath: {{ .mountPath }}
                {{- if .subPath }}
                subPath: {{ .subPath }}
                {{- end }}
            {{- end }}
            command: ["flyway","migrate", "-configFiles=/flyway/conf/flyway.conf" ,"-locations=filesystem:/flyway/sql" , "-connectRetries=60"] 
        {{- end }}
        volumes:
        {{- range .Values.volumes }}
          - name: {{ .name }}
            {{- if .configMapName }}
            configMap:
              name: {{ .configMapName }}
            {{- end }}
            {{- if .secretName }}
            secret:
              secretName: {{ .secretName }}
            {{- end }}
        {{- end }}