apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka-virtual-service
  namespace: consumer
spec:
  hosts:
    - dev-kafka.consumer.svc.cluster.local
  tcp:
    - match:
        - port: 9092
      route:
        - destination:
            host: dev-kafka.consumer.svc.cluster.local
            port:
              number: 9092