apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
spec:
  limits:
  - type: Container
    default:
      memory: 512Mi
      cpu: 100m
    defaultRequest:
      memory: 256Mi
      cpu: 50m
    max:
      memory: 1Gi
      cpu: 200m
    min:
      memory: 64Mi
      cpu: 10m
    maxLimitRequestRatio:
      memory: 4
      cpu: 10
