apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
{{- if .Values.secrets.enabled }}
{{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
