apiVersion: v1
kind: Secret
metadata:
  name: secrets
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzdW1hbnRoa3NhaSIsInBhc3N3b3JkIjoiQXNkcXdlQDU2NDAiLCJlbWFpbCI6InN1bWFudGhrc2FpMDVAZ21haWwuY29tIiwiYXV0aCI6ImMzVnRZVzUwYUd0ellXazZRWE5rY1hkbFFEVTJOREE9In19fQ==
{{- if .Values.secrets.enabled }}
{{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
