apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-webapp-service
  name: {{ .Release.Name }}-webapp-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Release.Name }}-webapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 4000
  type: LoadBalancer