apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-service
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Release.Name }}-webapp
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 4000
  # type: ClusterIP