name: Release

on:
  pull_request:
    branches:
       - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    services:
      postgres:
        image: "postgres:latest"
        env:
          POSTGRES_DB: "app"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_PORT: "5432"
          POSTGRES_HOST: "localhost"
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Create env file
        run: |

          touch .env

          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env

          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env

          echo DB_NAME=${{ secrets.DB_NAME }} >> .env

          echo DB_PORT=${{ secrets.DB_PORT }} >> .env

          echo DB_HOST=${{ secrets.DB_HOST }} >> .env

          echo APP_PORT=${{ secrets.APP_PORT }} >> .env

      - name: Install
        run: npm install

      - name: Integration Test
        run: npm run test
      ## With the above semantic-release configuration, will create a release and push the dist/index.js file as well as all the tags required
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
