name: Helm CI

on:
  pull_request:
    branches:
      - main 

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Lint Helm Chart
        run: helm lint
        working-directory: ./webapp-chart
      - name: Lint Helm Chart
        run: helm lint
        working-directory: ./namespace-helm-chart

      - name: Test Helm Chart
        run: |
          helm template .
        working-directory: ./namespace-helm-chart
      - name: Test Helm Chart
        run: |
          helm template .
        working-directory: ./webapp-chart
