name: Helm CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'

      - name: test
        run: ls

      - name: Lint Helm Chart
        run: helm lint .

      - name: Test Helm Chart
        run: |
          helm template . | kubeval --strict --ignore-missing-schemas
        
